version: "3"
services:

  server:
    image: dailt/auction:latest
    volumes:
      - .:/app
    network_mode: "host"
    environment:
      DB_HOST: 0.0.0.0
      DB_PORT: 5432
      DB_USER: docker
      DB_PASS: docker
      DB_NAME: auction
    command: sleep infinity


  postgis:
    image: kartoza/postgis:12.0
    network_mode: "host"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      USERNAME: docker
      PASS: docker
      POSTGRES_DBNAME: auction

volumes:
  db-data: